In [2]:
import pandas as pd
import numpy as np

In [3]:
url_cannoli = "https://github.com/2025-2-NCC5/Projeto6/raw/main/documentos/dados_cannoli.xlsx"

df_cannoli = pd.read_excel(url_cannoli, engine='openpyxl')

display(df_cannoli.head())
display(df_cannoli.info())

id   companyId containerId           createdAt  customer displayId  \
0   1  I0VP1DZXGU    AKVXT2FH 2025-01-08 15:47:00       525    O8CC98   
1   2  04MEUULZ6W    KKMY5TG5 2024-11-03 22:30:00       694    HJ99VA   
2   3  W2ZZS7CCZW    I87JLGTV 2024-09-09 05:49:00       491    XJJDH2   
3   4  SQ5MBL8L24    W3ZXOQHO 2025-05-22 06:22:00       846    J8QDM3   
4   5  0RCNJ6BRJD    NA0C0FOS 2025-02-22 01:23:00        77    H4LV73   

  engineId   engineName engineType  \
0   E3R037  DirectOrder        POS   
1   EJVOBV  DirectOrder        APP   
2   UDX1ZF       KDSPro        POS   
3   30FLOC       KDSPro        WEB   
4   QI3URN       KDSPro        POS   

                                      extraInfo  ...  orderTiming  orderType  \
0  Adipisci maiores nam eius vero nesciunt sed.  ...    IMMEDIATE   DELIVERY   
1                                           NaN  ...    IMMEDIATE   DELIVERY   
2                                           NaN  ...    IMMEDIATE     INDOOR   
3                Autem mollitia voluptas quasi.  ...    SCHEDULED    TAKEOUT   
4                                           NaN  ...    SCHEDULED   DELIVERY   

   salesChannel         scheduledAt      status preparationTime  \
0       ANOTAAI                 NaT  DISPATCHED              45   
1      WHATSAPP                 NaT   CONCLUDED              33   
2       EPADOCA                 NaT   CONCLUDED              22   
3        99FOOD 2025-05-22 14:22:00    CANCELED              35   
4        99FOOD 2025-02-24 11:23:00  DISPATCHED              20   

  takeOutTimeInSeconds totalAmount           updatedAt  version  
0                 2131       90.91 2025-01-09 03:32:00   v3.7.8  
1                  374       99.69 2024-11-04 03:05:00   v2.3.0  
2                  247       45.97 2024-09-09 09:32:00   v1.9.5  
3                 1766      104.31 2025-05-22 21:39:00   v2.8.5  
4                 1219       105.5 2025-02-22 13:53:00   v2.1.3  

[5 rows x 23 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   id                    2000 non-null   int64         
 1   companyId             2000 non-null   object        
 2   containerId           2000 non-null   object        
 3   createdAt             2000 non-null   datetime64[ns]
 4   customer              2000 non-null   int64         
 5   displayId             2000 non-null   object        
 6   engineId              2000 non-null   object        
 7   engineName            2000 non-null   object        
 8   engineType            2000 non-null   object        
 9   extraInfo             819 non-null    object        
 10  integrated            2000 non-null   bool          
 11  integrationId         2000 non-null   int64         
 12  isTest                2000 non-null   bool          
 13  orderTiming       

None

In [4]:
numerical_columns = ['preparationTime', 'takeOutTimeInSeconds', 'totalAmount']
df_numerical_subset = df_cannoli[numerical_columns]

display(df_numerical_subset.head())

preparationTime  takeOutTimeInSeconds totalAmount
0               45                  2131       90.91
1               33                   374       99.69
2               22                   247       45.97
3               35                  1766      104.31
4               20                  1219       105.5

Converte os dados numéricos selecionados em matrizes NumPy (vetores e matrizes) e imprima suas formas.

In [5]:
data_matrix = df_numerical_subset.values

data_vector = data_matrix[0, :]

print("Shape of data_matrix:", data_matrix.shape)
print("Shape of data_vector:", data_vector.shape)

Shape of data_matrix: (2000, 3)
Shape of data_vector: (3,)


Implementar e demonstrar operações básicas de álgebra linear (por exemplo, adição, multiplicação, transposição) usando NumPy nos vetores e matrizes criados.

In [6]:
# Certifica-se de que todas as colunas no subconjunto numérico são numéricas
for col in df_numerical_subset.columns:
    df_numerical_subset[col] = pd.to_numeric(df_numerical_subset[col], errors='coerce')

# Remove linhas com valores NaN que podem ter resultado da coerção
df_numerical_subset = df_numerical_subset.dropna()

# Converte o DataFrame numérico limpo em um array NumPy (matriz)
data_matrix = df_numerical_subset.values

# 1. Demonstra a transposição da matriz
data_matrix_transposed = data_matrix.T
print("Forma da matriz transposta:", data_matrix_transposed.shape)

# 2. Seleciona duas linhas para representar vetores
# Garante que há pelo menos duas linhas após remover NaNs
if data_matrix.shape[0] >= 2:
    vector1 = data_matrix[0, :]
    vector2 = data_matrix[1, :]

    # 3. Realiza a adição de vetores
    vector_sum = vector1 + vector2
    print("\nResultado da adição de vetores:")
    print(vector_sum)
else:
    print("\nNão há linhas suficientes na data_matrix para realizar a adição de vetores.")


# 4. Seleciona uma coluna para representar um vetor
# Garante que há pelo menos uma coluna
if data_matrix.shape[1] >= 1:
    column_vector = data_matrix[:, 0]

    # 5. Realiza a multiplicação escalar
    scalar = 2
    scaled_vector = column_vector * scalar
    print("\nResultado da multiplicação escalar:")
    print(scaled_vector)
else:
    print("\nNão há colunas suficientes na data_matrix para selecionar um vetor coluna.")

# 6. Seleciona duas matrizes compatíveis e realiza a multiplicação de matrizes
# Seleciona as 2 primeiras linhas e as 2 primeiras colunas
if data_matrix.shape[0] >= 2 and data_matrix.shape[1] >= 2:
    matrix1 = data_matrix[:2, :2]
    # Seleciona as 2 primeiras linhas e as 2 últimas colunas
    matrix2 = data_matrix[:2, 1:]

    # Realiza a multiplicação de matrizes
    # Verifica se as matrizes são compatíveis para multiplicação (o número de colunas na matrix1 deve ser igual ao número de linhas na matrix2)
    if matrix1.shape[1] == matrix2.shape[0]:
        matrix_product = np.dot(matrix1, matrix2)
        print("\nResultado da multiplicação de matrizes:")
        print(matrix_product)
        print("Forma da matriz resultante:", matrix_product.shape)
    else:
        print("\nAs matrizes não são compatíveis para multiplicação.")
        print("Forma da matrix1:", matrix1.shape)
        print("Forma da matrix2:", matrix2.shape)
else:
    print("\nA matriz de dados é muito pequena para selecionar matrizes compatíveis para multiplicação.")

Forma da matriz transposta: (3, 1917)

Resultado da adição de vetores:
[  78.  2505.   190.6]

Resultado da multiplicação escalar:
[ 90.  66.  44. ...  46.  38. 156.]

Resultado da multiplicação de matrizes:
[[892889.   216530.34]
 [210199.    40284.09]]
Forma da matriz resultante: (2, 2)


/tmp/ipython-input-3358094872.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_numerical_subset[col] = pd.to_numeric(df_numerical_subset[col], errors='coerce')
